Create a centralised cache manager
hyperledger/firefly pull request #1005
Opened 2022-08-25 09:43 UTC by Chengxuan

Create a centralised cache manager as described in #943

2022-08-30 13:44 UTC, Chengxuan commented
@awrichar comment addressed, will deal with the merge conflict next

2022-08-30 18:05 UTC, Chengxuan commented
@awrichar ready for review again.

2022-09-01 16:22 UTC, Chengxuan reviewed
Ready to be reviewed again

2022-09-01 23:54 UTC, peterbroadhurst commented
I see the fabric tests failed - downloading looks to look for root cause

2022-09-01 23:56 UTC, peterbroadhurst requested changes
Seeing this failure in the fabric tests on this line:

https://github.com/hyperledger/firefly/blob/e0aa9d78ee0e061efe9fc0a25e1cc3a12de39b57/internal/blockchain/fabric/fabric.go#L855

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb14a5d]

goroutine 8 [running]:
github.com/hyperledger/firefly/internal/blockchain/fabric.(*Fabric).GetNetworkVersion(0xc0004a4500, {0x103e9f0, 0xc000179780}, 0x96a5a5bc2e184b3e)
	/firefly/internal/blockchain/fabric/fabric.go:855 +0x9d
github.com/hyperledger/firefly/internal/multiparty.(*multipartyManager).configureContractCommon(0xc0004b1860, {0x103e9f0, 0xc000179780}, 0x0)
	/firefly/internal/multiparty/manager.go:152 +0x1fe
github.com/hyperledger/firefly/internal/multiparty.(*multipartyManager).ConfigureContract(0x1, {0x103e9f0, 0xc000179780})
	/firefly/internal/multiparty/manager.go:135 +0x25
github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).initManagers(0xc000220b40, {0x103e9f0, 0xc000179780})
	/firefly/internal/orchestrator/orchestrator.go:418 +0x317
github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).initComponents(0xc000220b40, {0x103e9f0, 0xc000179780})
	/firefly/internal/orchestrator/orchestrator.go:501 +0xe5
github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).Init(0xc000220b40, {0x103e9f0, 0xc000179740}, 0xc0004b5fa4)
	/firefly/internal/orchestrator/orchestrator.go:227 +0x12f
github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).initNamespace(0xc0004c2370, {0x103e9f0, 0xc00047e000}, 0xc0004a4b00)
	/firefly/internal/namespace/manager.go:312 +0x5b4
github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).Init(0xc0004c2370, {0x103e9f0, 0xc00047e000}, 0x1, 0xc000345f20)
	/firefly/internal/namespace/manager.go:223 +0x1e5
github.com/hyperledger/firefly/cmd.startFirefly({0x103e9f0, 0xc00047e000}, 0x0, {0x10526d0, 0xc0004c2370}, {0x1029140, 0xc00047f400}, 0x0, 0x0, 0xc000170060)
	/firefly/cmd/firefly.go:188 +0x49f
created by github.com/hyperledger/firefly/cmd.run
	/firefly/cmd/firefly.go:132 +0x4da
```

2022-09-02 05:26 UTC, Chengxuan commented
@peterbroadhurst thanks for the review. It’s caused by a mistake in the merge. I’ve fixed it and added more tests to catch it earlier. Spotted another error as well. Ready to be reviewed again

2022-09-02 12:44 UTC, peterbroadhurst commented on internal/coremsgs/en_config_descriptions.go
> +	ConfigCacheTransactionSize         = ffc("config.cache.transaction.size", "Max size of cached transactions", i18n.IntType)
Want to just confirm this is a byte sized object (not a count).

2022-09-02 12:46 UTC, peterbroadhurst commented on internal/coremsgs/en_config_descriptions.go
> +	ConfigCacheMessageSize             = ffc("config.cache.message.size", "Max size of cached messages for data manager", i18n.IntType)
See you have `i18n.IntType` here, but because it's a `.size` is will be `i18n.ByteSizeType`

2022-09-02 14:25 UTC, Chengxuan commented on internal/cache/cache.go
> +	cache, exists := cm.configuredCaches[cacheName]
this is a good point. I'll keep it in mind. Too used to node.js. Will add that in

2022-09-02 16:17 UTC, merged