Fix the example ff deploy command to specify ethereum
hyperledger/firefly pull request #1076
Opened 2022-09-27 12:33 UTC by matthew1001

Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>

2022-09-27 20:11 UTC, nguyer requested changes

2022-09-27 20:11 UTC, nguyer commented on docs/tutorials/custom_contracts/ethereum.md
>  $ ff deploy dev simple_storage.json
```suggestion
$ ff deploy ethereum dev simple_storage.json
```

2022-10-12 08:23 UTC, matthew1001 commented
Sorry completely missed your suggest change until today @nguyer Should all be good now.

2022-10-17 16:11 UTC, shorsher approved these changes

2022-10-17 16:20 UTC, nguyer approved these changes

2022-10-17 16:20 UTC, merged