Use separate event stream per namespace
hyperledger/firefly pull request #1388
Opened 2023-08-10 20:53 UTC by nguyer

This PR resolves https://github.com/hyperledger/firefly/issues/1381

Because we are moving from a single event stream to one per namespace, existing subscriptions will be recreated and events will be replayed on a new event stream the first time a FireFly Core node starts with these changes. Otherwise there is no user impacting change in this PR.

Event streams now follow the format `<plugin_topic_name>/<namespace_name>`. For example, event stream for the `default` namespace with a plugin topic of `0` would now be: `0/default`.

There is still outstanding work to do in the tokens plugin and tokens connectors, but I'm splitting those out into separate PRs.

2023-08-31 18:48 UTC, nguyer commented
If we have multiple namespaces using the same token connector (which I think is a valid configuration) with these changes FireFly would create multiple WebSocket connections to that one token connector which may not work correctly until the token connectors themselves are updated. I'm not sure if that's an issue or not.

2023-08-31 20:02 UTC, peterbroadhurst requested changes
This is a great piece of work @nguyer 👍 

A few comments/requests to think through.

2023-08-31 20:03 UTC, nguyer commented on internal/blockchain/fabric/fabric.go
> +func (f *Fabric) StartNamespace(ctx context.Context, namespace string) (err error) {
This is a good call out. I'm investigating this...

2023-08-31 20:14 UTC, nguyer commented on internal/orchestrator/orchestrator.go
> +	err := plugins.Blockchain.Plugin.StopNamespace(ctx, ns.Name)
It's probably just in the wrong spot. I'll move it. Thanks.

2023-11-15 16:55 UTC, nguyer commented on internal/orchestrator/orchestrator.go
> +	err := plugins.Blockchain.Plugin.StopNamespace(ctx, ns.Name)
Looking at this one again... it doesn't look like `Stop` gets called from `Purge`. Should it? Or does something else call both of them?

2024-02-15 22:01 UTC, peterbroadhurst approved these changes
There are a few minor additional comments from me to think about @nguyer, but none are a blocker to getting this important piece of work into mainline and progressing forwards to a release.

2024-02-21 21:40 UTC, nguyer commented on internal/blockchain/ethereum/ethereum.go
> +		wsconn.Close()
Hmm. I added a wait for this here, but it then gets into a deadlock trying to stop the namespace
```go
if ok {
    <-e.closed[namespace]
    wsconn.Close()
}
```

2024-02-21 21:40 UTC, nguyer commented on internal/blockchain/ethereum/ethereum.go
> +	go e.eventLoop(namespace, e.wsconn[namespace], e.closed[namespace])
Thanks. Added below in the event loop

2024-02-21 21:45 UTC, nguyer commented on internal/blockchain/fabric/fabric.go
> +func (f *Fabric) StartNamespace(ctx context.Context, namespace string) (err error) {
Noted in: https://github.com/hyperledger/firefly/pull/1461/files#diff-b2e77d2a6574b8e68136b226be7c14dff6897e0c30751d33585d9d2bb916cea9R65

2024-02-21 21:48 UTC, nguyer commented
I am also noting that the Tezos plugin was developed in parallel to this PR so it does not have these changes. However, TezosConnect does not yet have evenstream support implemented. Once Tezosconnect supports eventstreams we should circle back and make these same changes there too. If I were to do the changes as part of this PR today I wouldn't be able to test them, so I think it's best to hold off for now.

2024-03-04 15:44 UTC, merged