Tezos Connector map converter
hyperledger/firefly pull request #1451
Opened 2024-01-23 08:49 UTC by alex-semenyuk

FFI JSON map_init for `POST /contracts/interfaces`

```
{
   "namespace":"default",
   "name":"map",
   "version":"v1.0.0",
   "description":"Map impl",
   "methods":[
      {
         "name":"init_map",
         "pathname":"",
         "description":"",
         "params":[
            {
               "name":"newValue",
               "schema":{
                  "type":"object",
                  "details":{
                     "type": "schema",
                     "internalSchema": {
                        "type": "map",
                        "args": [
                            {
                               "name": "key",
                               "type": "integer"
                            },
                            {
                               "name": "value",
                               "type": "string"
                            }
                        ]     
                     }
                  }
               }
            }
         ],
         "returns":[]
      }
   ],
   "events":[]
}
```

2024-01-23 12:14 UTC, denisandreenko commented
This is great, thank you @alex-semenyuk!

2024-01-23 12:14 UTC, denisandreenko approved these changes

2024-01-23 17:07 UTC, nguyer requested changes
Thanks for contributing this! The code itself looks good, but the linter would like you to update the copyright year. Sorry it's very picky 🙃 

```
Error: internal/blockchain/tezos/ffi2michelson.go:1:17: Expected:2024, Actual: 2023
```

2024-01-23 17:18 UTC, alex-semenyuk commented
> Thanks for contributing this! The code itself looks good, but the linter would like you to update the copyright year. Sorry it's very picky 🙃
> 
> ```
> Error: internal/blockchain/tezos/ffi2michelson.go:1:17: Expected:2024, Actual: 2023
> ```

@nguyer sure, should be ok now

2024-02-09 21:13 UTC, denisandreenko approved these changes

2024-02-12 21:20 UTC, nguyer approved these changes

2024-02-12 21:46 UTC, merged