Adding check URLs to GH actions
hyperledger/firefly pull request #1518
Opened 2024-05-28 20:04 UTC by dwertent

I've noticed some invalid URLs in the repository. This GitHub Action will help detect these invalid URLs when opening a pull request or during a scheduled scan. I recommend setting `force_pass` to `false` to prevent the approval of pull requests containing invalid URLs. You can see an example [here](https://github.com/dwertent/firefly/actions/runs/9275582818/job/25520636370#step:4:351).

![image](https://github.com/hyperledger/firefly/assets/64066841/61982b9f-91fe-4fab-b916-9c8ba1014630)

2024-05-29 06:37 UTC, dwertent commented
Working on this PR made me realize that the package should support SARIF format output. As a result, I opened [this PR](https://github.com/urlstechie/urlchecker-python/pull/91) and [this PR](https://github.com/urlstechie/urlchecker-action/pull/109) to enhance the informativeness of the GitHub Action results.

2024-07-08 15:13 UTC, EnriqueL8 requested changes
Thanks for the contribution here

I'm torn on the force pass always being `true` as we won't notice if thing have broken without looking at logs but at the same time I don't want this to gate PRs into the repo 

So if there is a way to be notified that it has failed on the schedule it would be good.

As part of this PR would be a great contribution if the existing URL highlighted in the description are fixed as well

2024-07-08 15:16 UTC, EnriqueL8 commented on .github/workflows/url_checker.yml
> +        exclude_patterns: 127.0.0.1,localhost,ipfs_,ca_org,ethconnect_,dataexchange_
Also add `tokens_0_0` here

2024-07-08 15:17 UTC, EnriqueL8 commented
I can't edit my review seems like you put in your description `I recommend setting force_pass to false to prevent the approval of pull requests containing invalid URLs.` that is valid to me then

2024-08-13 19:26 UTC, closed without merging