Document support in v1.3.2 for large JSON numbers
hyperledger/firefly pull request #1577
Opened 2024-09-12 09:11 UTC by matthew1001

See issue https://github.com/hyperledger/firefly/issues/1568

This PR documents the new large-number support. For convenience, here's a preview of the updated topic:

![image](https://github.com/user-attachments/assets/9c037a86-8e5f-4eef-a12b-69d5cf0fe548)

2024-09-12 10:14 UTC, EnriqueL8 commented on doc-site/docs/reference/types/_includes/ffbigint_description.md
> +## Maximum size of numbers in versions of FireFly up to `v1.3.1`
Looks good but I wouldn't only had this section in the ffbigint description as it's quite nested down in the documentation under reference. We need to document this in two other places:
- Doc around invoking a smart contract through the API
- Release notes for v1.3.2

2024-09-12 10:15 UTC, EnriqueL8 commented on doc-site/docs/reference/types/_includes/ffbigint_description.md
> +## Maximum size of numbers in versions of FireFly up to `v1.3.1`
Thinking something in the interface format https://hyperledger.github.io/firefly/latest/reference/firefly_interface_format/#schema

2024-09-12 10:16 UTC, EnriqueL8 commented on doc-site/docs/reference/types/_includes/ffbigint_description.md
> +## Maximum size of numbers in versions of FireFly up to `v1.3.1`
For example you can see in the simple invoke EVM contract tutorial we use a number https://hyperledger.github.io/firefly/latest/tutorials/custom_contracts/ethereum/#invoke-the-smart-contract

2024-09-13 10:40 UTC, EnriqueL8 requested changes

2024-09-13 10:40 UTC, EnriqueL8 commented on doc-site/docs/releasenotes/index.md
> +    See [Brew](../)
missing the link here to brew

2024-09-13 10:44 UTC, matthew1001 commented on doc-site/docs/releasenotes/index.md
> +    See [Brew](../)
Bah, my bad.

2024-09-13 11:53 UTC, EnriqueL8 commented
Will fix codecov in a follow up PR

2024-09-13 11:53 UTC, merged