FAQ and FireFly Tutorial Updates
hyperledger/firefly pull request #857
Opened 2022-06-10 17:19 UTC by trevorsc19

Two main changes in this PR:
1- FAQ updates. Added some FAQs related to deploying smart contracts, connecting to Metamask, and how FireFly enables multi-chain applications
2- FireFly tutorial updates. Fixed some links to swagger pages that were outdated, updated some instructions, added instructions and screenshots on using the FireFly sandbox in order to follow along some of the examples given in the tutorials

2022-06-14 17:26 UTC, nguyer requested changes
Just a couple of minor spelling things. Also a couple notes on the FAQs. Up to you, how much you want to incorporate those. Otherwise looks good, thanks!

2022-06-14 17:27 UTC, nguyer commented
It also looks like the docs build has failed. To test this locally, you can run `make docs` to ensure all the checks pass.

2022-07-01 18:06 UTC, trevorsc19 commented
I've made changes based on the comments from Nicko. Running `make docs` fails due to some missing alt attributes and one external link issue. Fixing those now and will push again

2022-07-05 20:54 UTC, shorsher approved these changes
Looks good to me, but I'll let @nguyer give the final pass.

2022-07-06 19:05 UTC, nguyer requested changes
There's just one section that should be removed, but otherwise looks good. Thanks!

2022-07-06 19:33 UTC, nguyer commented on docs/faqs/faqs.md
> +
Should this have content in it? Or should we wait to add the header until we have the content ready?

2022-07-06 22:16 UTC, nguyer approved these changes
Looks good! Thanks @trevorsc19

2022-07-06 22:17 UTC, merged